// ScanOrchestrator.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using SmartFileOrganizer.Core.Interfaces;
using SmartFileOrganizer.Core.Models;
using SmartFileOrganizer.Application;

namespace SmartFileOrganizer.Application.Services
{
    /// <summary>
    /// Orchestrates a complete scan operation:
    ///   1. Enumerates files via IFileScanner.
    ///   2. Creates FileRecord objects.
    ///   3. Detects duplicates using DuplicateEngine.
    ///   4. Persists ScanSession and DuplicateGroup results.
    ///   5. Reports progress via IProgress<ScanProgressReport>.
    /// Supports cancellation.
    /// </summary>
    public class ScanOrchestrator
    {
        private readonly IFileScanner _fileScanner;
        private readonly IHashService _hashService;
        private readonly IRepository _repository;
        private readonly DuplicateEngine _duplicateEngine;

        public ScanOrchestrator(
            IFileScanner fileScanner,
            IHashService hashService,
            IRepository repository,
            DuplicateEngine duplicateEngine)
        {
            _fileScanner = fileScanner ?? throw new ArgumentNullException(nameof(fileScanner));
            _hashService = hashService ?? throw new ArgumentNullException(nameof(hashService));
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _duplicateEngine = duplicateEngine ?? throw new ArgumentNullException(nameof(duplicateEngine));
        }

        public async Task RunAsync(string rootPath, IProgress<ScanProgressReport> progress, CancellationToken cancellationToken)
        {
            if (string.IsNullOrWhiteSpace(rootPath))
                throw new ArgumentException("Root path must be provided", nameof(rootPath));

            var discovered = new List<FileRecord>();
            int filesDiscovered = 0;
            int filesAnalyzed = 0;

            // Stage 1: enumeration
            progress?.Report(new ScanProgressReport
            {
                FilesDiscovered = filesDiscovered,
                FilesAnalyzed = filesAnalyzed,
                CurrentFile = string.Empty,
                Stage = "Enumerating",
                Percentage = 0
            });

            await foreach (var filePath in _fileScanner.ScanAsync(rootPath, cancellationToken))
            {
                cancellationToken.ThrowIfCancellationRequested();
                filesDiscovered++;
                progress?.Report(new ScanProgressReport
                {
                    FilesDiscovered = filesDiscovered,
                    FilesAnalyzed = filesAnalyzed,
                    CurrentFile = filePath,
                    Stage = "Enumerating",
                    Percentage = 0
                });

                var info = new FileInfo(filePath);
                var record = new FileRecord
                {
                    Path = filePath,
                    Size = info.Length,
                    Created = info.CreationTimeUtc,
                    Modified = info.LastWriteTimeUtc
                };
                discovered.Add(record);
            }

            // Stage 2: hashing (partial & full) – required by DuplicateEngine internally.
            // The DuplicateEngine will call the hash service, but we ensure hashes are cached for future scans.
            // For simplicity we skip explicit caching here.

            // Report before duplicate detection
            progress?.Report(new ScanProgressReport
            {
                FilesDiscovered = filesDiscovered,
                FilesAnalyzed = filesAnalyzed,
                CurrentFile = string.Empty,
                Stage = "Detecting Duplicates",
                Percentage = 0
            });

            var duplicateGroups = await _duplicateEngine.DetectDuplicatesAsync(discovered, cancellationToken);

            // Stage 3: persist results
            var session = new ScanSession
            {
                // Assuming ScanSession has at least Id and Timestamp properties – if not, they can be added later.
                // For now we only set a Timestamp.
                // Id is auto‑generated by the repository.
                // The class currently only contains properties (not shown). We'll set a simple Timestamp if present.
            };
            await _repository.SaveScanSessionAsync(session, cancellationToken);
            foreach (var group in duplicateGroups)
            {
                await _repository.SaveDuplicateGroupAsync(group, cancellationToken);
            }

            // Final progress report
            progress?.Report(new ScanProgressReport
            {
                FilesDiscovered = filesDiscovered,
                FilesAnalyzed = filesDiscovered,
                CurrentFile = string.Empty,
                Stage = "Completed",
                Percentage = 100
            });
        }
    }
}
