// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFileOrganizer.Infrastructure.Data;

#nullable disable

namespace SmartFileOrganizer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowPermanentDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoScanEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryExtensionMap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfirmBeforeEachOperation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultScanFolders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedFolders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeHiddenFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSystemFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("MaximumFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MinimizeToTray")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinimumFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MoveToRecycleBinByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParallelismLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.DuplicateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecoverableSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DuplicateGroups");
                });

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.FileRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuplicateGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateGroupId");

                    b.ToTable("FileRecord");
                });

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.OperationHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperationHistory");
                });

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.ScanSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanSessions");
                });

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.FileRecord", b =>
                {
                    b.HasOne("SmartFileOrganizer.Core.Models.DuplicateGroup", null)
                        .WithMany("Files")
                        .HasForeignKey("DuplicateGroupId");
                });

            modelBuilder.Entity("SmartFileOrganizer.Core.Models.DuplicateGroup", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
